version: "3.8"

services:
  oidcserver:
    image: oidcserver:latest
    container_name: oidcserver
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik-net
    ports:
      - 9998:9998
    labels:
      - traefik.enable=true
      - traefik.http.routers.oidcserver.rule=Host(`oidcserver.dev.localhost`) && PathPrefix("/oidc")
      - traefik.http.routers.oidcserver.middlewares=strip_prefix_1 # check docs to exclude requests from compression
      - traefik.http.middlewares.strip_prefix_1.stripprefix.prefixes=/oidc
      - traefik.docker.network=traefik-net
      - traefik.http.routers.oidcserver.entrypoints=websecure
      - traefik.http.routers.oidcserver.tls=true
      - traefik.http.services.oidcserver.loadbalancer.server.port=9998
    restart: unless-stopped

networks:
  traefik-net:
    name: traefik-net
    external: true
